#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import subprocess
import shutil

lockfile = "Pipfile.lock"
versioned_lockfile = f"{lockfile}.{sys.version_info.major}.{sys.version_info.minor}"

my_args = sys.argv[1:]

print(f"using lockfile {versioned_lockfile}")
print(f"args: {my_args}")

shutil.copy(versioned_lockfile, lockfile)
subprocess.check_call([sys.executable, "-m", "pipenv"] + my_args)
